

SELECT * FROM APOIADOR
WHERE ((SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'NUBIA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'ELIZABETH')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'TANIA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'WANESSA')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'CECILIA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'KENIA')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'VILMA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'NEIDE')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE '') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE '')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE '') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE '')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE '') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE '')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE '') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE ''))
AND IdApoiador > 0 AND Sexo IS NULL;

SELECT DISTINCT SUBSTRING_INDEX(Nome, ' ', 1), COUNT(SUBSTRING_INDEX(Nome, ' ', 1)) FROM APOIADOR
WHERE SEXO IS NULL
-- AND RIGHT(SUBSTRING_INDEX(Nome, ' ', 1), 2) IN ('EL') 
-- AND Nome NOT LIKE 'Santana%' AND Nome NOT LIKE 'UBIRAJARA%' 
-- AND Nome NOT LIKE 'MOREIRA%' AND Nome NOT LIKE 'DUTRA%'
GROUP BY SUBSTRING_INDEX(Nome, ' ', 1)
ORDER BY COUNT(SUBSTRING_INDEX(Nome, ' ', 1)) DESC;



SELECT * FROM APOIADOR
WHERE (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'SAMUEL') 
AND IdApoiador > 0;



SELECT SUBSTRING_INDEX(Nome, ' ', 1) AS primeiro_nome
FROM APOIADOR;

SELECT * FROM APOIADOR WHERE Sexo IS  NULL;


UPDATE APOIADOR
SET Sexo = 'FEMININO'
WHERE ((SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'SARAH') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'KELLY')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'LEILA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'MICHELLE')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'SELMA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'MARILIA')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'FATIMA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'SUELY')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'ELISANGELA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'EVA')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'VITORIA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'CAROLINE')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'ERIKA') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'NILVA')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'MARILENE') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'MARILENE'))
AND IdApoiador > 0 AND Sexo IS NULL;