

SELECT * FROM APOIADOR
WHERE (
(SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'DOUGLAS') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'NELSON')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'VALDIR') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'DAVID')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'CRISTIANO') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'SAULO')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'AUGUSTO') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'MILTON')
)
AND IdApoiador > 0 AND Sexo IS NULL;

SELECT DISTINCT SUBSTRING_INDEX(Nome, ' ', 1), COUNT(SUBSTRING_INDEX(Nome, ' ', 1)) FROM APOIADOR
WHERE SEXO IS NULL
-- AND RIGHT(SUBSTRING_INDEX(Nome, ' ', 1), 2) IN ('EL') 
-- AND Nome NOT LIKE 'Santana%' AND Nome NOT LIKE 'UBIRAJARA%' 
-- AND Nome NOT LIKE 'MOREIRA%' AND Nome NOT LIKE 'DUTRA%'
GROUP BY SUBSTRING_INDEX(Nome, ' ', 1)
ORDER BY COUNT(SUBSTRING_INDEX(Nome, ' ', 1)) DESC;



SELECT * FROM APOIADOR
WHERE (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'SAMUEL') 
AND IdApoiador > 0;



SELECT SUBSTRING_INDEX(Nome, ' ', 1) AS primeiro_nome
FROM APOIADOR;

SELECT * FROM APOIADOR WHERE Sexo IS  NULL;


UPDATE APOIADOR
SET Sexo = 'MASCULINO'
WHERE (
(SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'DOUGLAS') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'NELSON')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'VALDIR') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'DAVID')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'CRISTIANO') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'SAULO')
OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'AUGUSTO') OR (SUBSTRING_INDEX(Nome, ' ', 1) LIKE 'MILTON')
)
AND IdApoiador > 0 AND Sexo IS NULL;





------------------------

ALTER TABLE APOIADOR ADD Genero VARCHAR(60);
