

SELECT * FROM APOIADOR
WHERE RIGHT(SUBSTRING_INDEX(Nome, ' ', 1), 2) IN ('RA') AND Nome NOT LIKE 'Santana%' AND Nome NOT LIKE 'UBIRAJARA%' 
AND Nome NOT LIKE 'MOREIRA%' AND Nome NOT LIKE 'DUTRA%'
AND IdApoiador > 0 AND Sexo IS NULL;

SELECT DISTINCT SUBSTRING_INDEX(Nome, ' ', 1), COUNT(SUBSTRING_INDEX(Nome, ' ', 1)) FROM APOIADOR
WHERE SEXO IS NULL
AND RIGHT(SUBSTRING_INDEX(Nome, ' ', 1), 2) IN ('EL') 
-- AND Nome NOT LIKE 'Santana%' AND Nome NOT LIKE 'UBIRAJARA%' 
-- AND Nome NOT LIKE 'MOREIRA%' AND Nome NOT LIKE 'DUTRA%'
GROUP BY SUBSTRING_INDEX(Nome, ' ', 1)
ORDER BY COUNT(SUBSTRING_INDEX(Nome, ' ', 1)) DESC;







SELECT SUBSTRING_INDEX(Nome, ' ', 1) AS primeiro_nome
FROM APOIADOR;



UPDATE APOIADOR
SET Sexo = 'FEMININO'
WHERE RIGHT(SUBSTRING_INDEX(Nome, ' ', 1), 2) IN ('RA') AND Nome NOT LIKE 'Santana%' AND Nome NOT LIKE 'UBIRAJARA%' 
AND Nome NOT LIKE 'MOREIRA%' AND Nome NOT LIKE 'DUTRA%'
AND IdApoiador > 0 AND Sexo IS NULL;